;;; cu-arcs-v2.scm -- Cepheus Universal Alien Race creation System, version 2.
;;; Creates intelligent aliens.
;;;
;;; awful --port=2020 cu-arcs-v2.scm
(include "alien-tables.scm")

(module cu-arcs ()

(import scheme)
(import (chicken base))
(import (chicken random))
(import (math base))
(import loop)
(import srfi-13)
(import awful)
(import alien-tables)

(include "roll-tables.scm")

(define-session-page (main-page-path)
  (lambda ()
    `((h3 "Alien Race Creation - Major or Minor Race")
      (form (@ (action "/major-minor-result"))
            (p "Do something with aliens!")
            (ol
             (li
              (p (b "Major or Minor Race"))
              (input (@ (type "radio")
                        (id "major-or-minor-major")
                        (name "major-or-minor")
                        (value "Major")
                        (checked)))
              (label (@ (for "major-or-minor-major"))
                     "Major")
              (input (@ (type "radio")
                        (id "major-or-minor-minor")
                        (name "major-or-minor")
                        (value "Minor")))
              (label (@ (for "major-or-minor-minor"))
                     "Minor")
              (br)
              (input (@ (type "submit")
                        (value "Submit")))
              "    "
              (input (@ (type "reset")
                        (value "Reset")))))))))

(define-session-page "/major-minor-result"
  (lambda ()
    (resolved-field! major-or-minor (if (string=? ($ "major-or-minor") "Major") 'Major 'Minor))
    `((h3 "The story so far")
      (p
       "Major or Minor Race: " (b ,($session 'major-or-minor)) (br))
       
      (h3 "Alien Race Creation - Homeworld")
      (form (@ (action "/alien-creation-result"))
            (p "Do something with aliens!")
            (ol

             (li (@ (value "2"))
              (p (b "Homeworld"))
              (ul
               (li (b "World Size")
                   (input (@ (type "radio")
                             (id "world-size-roll")
                             (name "world-size")
                             (value "Roll")
                             (checked)))
                   (label (@ (for "world-size-roll"))
                          "Roll 2D6+1")
                   (input (@ (type "radio")
                             (id "world-size-choose")
                             (name "world-size")
                             (value "Choose")))
                   (label (@ (for "world-size-chose"))
                          "Choose World Size: ")
                   " "
                   (label (@ (for "chosen-world-size"))
                          "3-13:")
                   (input (@ (type "number")
                             (id "chosen-world-size")
                             (name "chosen-world-size")
                             (min 3)
                             (max 13))))

               (li (b "Atmosphere")
                   (br)
                   (input (@ (type "radio")
                             (id "atmosphere-roll")
                             (name "atmosphere")
                             (value "Roll")
                             (checked)))
                   (label (@ (for "atmosphere-roll"))
                          "Roll 2D6; if Size 3-4 then roll 1D6+1")
                   (br)
                   (input (@ (type "radio")
                             (id "atmosphere-choose")
                             (name "atmosphere")
                             (value "Choose")))
                   (label (@ (for "atmosphere-choose"))
                          "Choose 2-12; if Size 3-4 then choose 2-7")
                   " "
                   (label (@ (for "chosen-atmosphere"))
                          "Chosen Atmosphere:")
                   (input (@ (type "number")
                             (id "chosen-atmosphere")
                             (name "chosen-atmosphere")
                             (min 2)
                             (max 12))))

               (li (b "Hydrographics")
                   (br)
                   (input (@ (type "radio")
                             (id "hydrographics-roll")
                             (name "hydrographics")
                             (value "Roll")
                             (checked)))
                   (label (@ (for "hydrographics-roll"))
                          "Roll 2D6-2; if Atmosphere 2-3 roll 1D6+1")
                   (br)
                   (input (@ (type "radio")
                             (id "hydrographics-choose")
                             (name "hydrographics")
                             (value "Choose")))
                   (label (@ (for "hydrographics-choose"))
                          "Choose: 0-10; if Atmosphere 2-3 choose 2-7")
                   " "
                   (label (@ (for "chosen-hydrographics"))
                          "Chosen Hydrographics:")
                   (input (@ (type "number")
                             (id "chosen-hydrographics")
                             (name "chosen-hydrographics")
                             (min 0)
                             (max 10))))

               (li (b "Population")
                   (br)
                   (input (@ (type "radio")
                             (id "population-roll")
                             (name "population")
                             (value "Roll")
                             (checked)))
                   (label (@ (for "population-roll"))
                          "If Minor Race roll 1D3+5; if Major Race roll 1D3+7")
                   (br)
                   (input (@ (type "radio")
                             (id "population-choose")
                             (name "population")
                             (value "Choose")))
                   (label (@ (for "population-choose"))
                          "If Minor Race choose 6-8; 
if Major race choose 8-10")
                   " "
                   (label (@ (for "chosen-population"))
                          "Chosen Population:")
                   (input (@ (type "number")
                             (id "chosen-population")
                             (name "chosen-population")
                             (min 6)
                             (max 10))))

               ,(formula-field-li 'government "Government" 1 6 (government-formula))

               (li (b "Law Level")
                   (br)
                   (input (@ (type "radio")
                             (id "law-level-roll")
                             (name "law-level")
                             (value "Roll")
                             (checked)))
                   (label (@ (for "law-level-roll"))
                          "Roll 2D6-2")
                   (br)
                   (input (@ (type "radio")
                             (id "law-level-choose")
                             (name "law-level")
                             (value "Choose")))
                   (label (@ (for "law-level-choose"))
                          "Choose 0-10")
                   " "
                   (label (@ (for "chosen-law-level"))
                          "Chosen Law Level:")
                   (input (@ (type "number")
                             (id "chosen-law-level")
                             (name "chosen-law-level")
                             (min 0)
                             (max 10))))

               ,(keyed-formula-field-li 'tech-level "Tech Level" 1 6 "Major or Minor Race" (tech-level-formula))

               ,(keyed-roll-field-li 'starport "Starport" 1 6 "Major or Minor Race" (starport-name)))
              (br)
              (input (@ (type "submit")
                        (value "Submit")))
              "    "
              (input (@ (type "reset")
                        (value "Reset")))))))))

(define-session-page "/alien-creation-result"
  (lambda ()
    (define major-or-minor ($session 'major-or-minor))
    (resolved-field! world-size (resolve-value world-size (+ (nD 2 6) 1)))
    (resolved-field! atmosphere
      (resolve-value atmosphere (if (<= 3 world-size 4) (+ (D 6) 1) (nD 2 6))))
    (resolved-field! hydrographics
      (resolve-value hydrographics (if (<= 2 atmosphere 3) (+ (D 6) 1) (- (nD 2 6) 2))))
    (resolved-field! population
      (resolve-value population (if (eq? major-or-minor 'Minor) (+ (D 3) 5) (+ (D 3) 7))))
    (resolved-field! government (resolve-formula-field government government-formula (D 6)))
    (resolved-field! law-level (resolve-value law-level (- (nD 2 6) 2)))
    (resolved-field! tech-level
      (resolve-keyed-formula-field tech-level tech-level-formula major-or-minor (D 6)))
    (resolved-field! starport (resolve-keyed-field starport starport-name major-or-minor (D 6)))

    `((h3 "The story so far")
      "Major or Minor Race: " (b ,major-or-minor) (br)
      "World Size: " (b ,world-size) (br)
      "Atmosphere: " (b ,atmosphere) (br)
      "Hydrographics: " (b ,hydrographics) (br)
      "Population: " (b ,population) (br)
      "Government: " (b ,government) (br)
      "Law Level: " (b ,law-level) (br)
      "Tech Level: " (b ,tech-level) (br)
      "Star Port: " (b ,starport) (br)
      (h3 "Biotype")
      ;; Another input form
      (form (@ (action "/alien-creation-result-2"))
            (p "Do something with aliens!")
            (ol

             (li (@ (value "3"))
                 (p (b "Biotype"))
                 (ul
                  ,(roll-field-li 'biotype "Biotype" 2 6 (biotype-name))
                  ,(keyed-roll-field-li 'subtype "Subtype" 2 6 "Biotype" (subtype-name))
                  )
                 (br)
                 (input (@ (type "submit")
                           (value "Submit")))
                 "    "
                 (input (@ (type "reset")
                           (value "Reset")))
                 ))))))

(define-session-page "/alien-creation-result-2"
  (lambda ()
    (define major-or-minor ($session 'major-or-minor))
    (define world-size ($session 'world-size))
    (define atmosphere ($session 'atmosphere))
    (define hydrographics ($session 'hydrographics))
    (define population ($session 'population))
    (define government ($session 'government))
    (define law-level ($session 'law-level))
    (define tech-level ($session 'tech-level))
    (define starport ($session 'starport))
    (resolved-field! biotype (resolve-field biotype biotype-name (nD 2 6)))
    (resolved-field! subtype (resolve-keyed-field subtype subtype-name biotype (nD 2 6)))

    `((h3 "The story so far")
      "Major or Minor Race: " (b ,major-or-minor) (br)
      "World Size: " (b ,world-size) (br)
      "Atmosphere: " (b ,atmosphere) (br)
      "Hydrographics: " (b ,hydrographics) (br)
      "Population: " (b ,population) (br)
      "Government: " (b ,government) (br)
      "Law Level: " (b ,law-level) (br)
      "Tech Level: " (b ,tech-level) (br)
      "Star Port: " (b ,starport) (br)
      "Biotype: " (b ,biotype) (br)
      "Subtype: " (b ,subtype) (br)
      (h3 "Reproduction")
      (form (@ (action "/alien-creation-result-3"))
            (p "Do something with aliens!")
            (ol
             (li (@ (value "4"))
                 (p (b "Reproduction"))
                 (ul
                  ,(roll-field-li 'sex "Sex" 2 6 (sex-name))
                  ,(roll-field-li 'reproduction "Reproduction" 1 6 (reproduction-name)))
                 (br)
                 (input (@ (type "submit")
                           (value "Submit")))
                 "    "
                 (input (@ (type "reset")
                           (value "Reset")))
                 ))))))

(define-session-page "/alien-creation-result-3"
  (lambda ()
    (define major-or-minor ($session 'major-or-minor))
    (define world-size ($session 'world-size))
    (define atmosphere ($session 'atmosphere))
    (define hydrographics ($session 'hydrographics))
    (define population ($session 'population))
    (define government ($session 'government))
    (define law-level ($session 'law-level))
    (define tech-level ($session 'tech-level))
    (define starport ($session 'starport))
    (define biotype ($session 'biotype))
    (define subtype ($session 'subtype))
    (resolved-field! sex (resolve-field sex resolve-sex (nD 2 6)))
    (resolved-field! reproduction (resolve-field reproduction reproduction-name (D 6)))

    `((h3 "The story so far")
      "Major or Minor Race: " (b ,major-or-minor) (br)
      "World Size: " (b ,world-size) (br)
      "Atmosphere: " (b ,atmosphere) (br)
      "Hydrographics: " (b ,hydrographics) (br)
      "Population: " (b ,population) (br)
      "Government: " (b ,government) (br)
      "Law Level: " (b ,law-level) (br)
      "Tech Level: " (b ,tech-level) (br)
      "Star Port: " (b ,starport) (br)
      "Biotype: " (b ,biotype) (br)
      "Subtype: " (b ,subtype) (br)
      "Sex: " (b ,sex) (br)
      "Reproduction: " (b ,reproduction) (br)
      (h3 "Amphibious?")
      (form (@ (action "/alien-creation-result-4"))
            (p "Do something with aliens!")
            (ol
             (li (@ (value "5"))
                 (p (b "Amphibious?"))
                 (ul
                  ,(roll-field-li 'amphibious "Amphibious" 2 6
                                  (amphibious-name (hydrographic-band hydrographics))))
                 (br)
                 (input (@ (type "submit")
                           (value "Submit")))
                 "    "
                 (input (@ (type "reset")
                           (value "Reset")))
                 ))))))

(define-session-page "/alien-creation-result-4"
  (lambda ()
    (define major-or-minor ($session 'major-or-minor))
    (define world-size ($session 'world-size))
    (define atmosphere ($session 'atmosphere))
    (define hydrographics ($session 'hydrographics))
    (define population ($session 'population))
    (define government ($session 'government))
    (define law-level ($session 'law-level))
    (define tech-level ($session 'tech-level))
    (define starport ($session 'starport))
    (define biotype ($session 'biotype))
    (define subtype ($session 'subtype))
    (define sex ($session 'sex))
    (define reproduction ($session 'reproduction))
    (resolved-field! amphibious
      (resolve-keyed-field amphibious amphibious-name (hydrographic-band hydrographics) (nD 2 6)))

    `((h3 "The story so far")
      "Major or Minor Race: " (b ,major-or-minor) (br)
      "World Size: " (b ,world-size) (br)
      "Atmosphere: " (b ,atmosphere) (br)
      "Hydrographics: " (b ,hydrographics) (br)
      "Population: " (b ,population) (br)
      "Government: " (b ,government) (br)
      "Law Level: " (b ,law-level) (br)
      "Tech Level: " (b ,tech-level) (br)
      "Star Port: " (b ,starport) (br)
      "Biotype: " (b ,biotype) (br)
      "Subtype: " (b ,subtype) (br)
      "Sex: " (b ,sex) (br)
      "Reproduction: " (b ,reproduction) (br)
      "Amphibious: " (b ,amphibious) (br)
      (h3 "Body Form")
      (p "If the race is a water-breather or amphibian, ignore a Walker or Flyer Locomotion result.")
      (form (@ (action "/alien-creation-result-5"))
            (p "Do something with aliens!")
            (ol
             (li (@ (value "6"))
                 (p (b "Body Form"))
                 (ul
                  ,(roll-field-li 'locomotion "Locomotion" 2 6 (locomotion-name))
                  ,(roll-field-li 'symmetry "Symmetry" 2 6 (symmetry-name))
                  ,(roll-field-li 'legs "Number of Legs" 2 6 (legs-count)))
                 (br)
                 (input (@ (type "submit")
                           (value "Submit")))
                 "    "
                 (input (@ (type "reset")
                           (value "Reset")))
                 ))))))

(define-session-page "/alien-creation-result-5"
  (lambda ()
    (define major-or-minor ($session 'major-or-minor))
    (define world-size ($session 'world-size))
    (define atmosphere ($session 'atmosphere))
    (define hydrographics ($session 'hydrographics))
    (define population ($session 'population))
    (define government ($session 'government))
    (define law-level ($session 'law-level))
    (define tech-level ($session 'tech-level))
    (define starport ($session 'starport))
    (define biotype ($session 'biotype))
    (define subtype ($session 'subtype))
    (define sex ($session 'sex))
    (define reproduction ($session 'reproduction))
    (define amphibious ($session 'amphibious))
    (resolved-field! locomotion (resolve-field locomotion locomotion-name (nD 2 6)))
    (resolved-field! symmetry (resolve-field symmetry symmetry-name (nD 2 6)))
    (resolved-field! legs (resolve-field legs legs-count (nD 2 6)))

    `((h3 "The story so far")
      "Major or Minor Race: " (b ,major-or-minor) (br)
      "World Size: " (b ,world-size) (br)
      "Atmosphere: " (b ,atmosphere) (br)
      "Hydrographics: " (b ,hydrographics) (br)
      "Population: " (b ,population) (br)
      "Government: " (b ,government) (br)
      "Law Level: " (b ,law-level) (br)
      "Tech Level: " (b ,tech-level) (br)
      "Star Port: " (b ,starport) (br)
      "Biotype: " (b ,biotype) (br)
      "Subtype: " (b ,subtype) (br)
      "Sex: " (b ,sex) (br)
      "Reproduction: " (b ,reproduction) (br)
      "Amphibious: " (b ,amphibious) (br)
      "Locomotion: " (b ,locomotion) (br)
      "Symmetry: " (b ,symmetry) (br)
      "Number of Legs: " (b ,legs) (br)
      (h3 "Size & Characteristics")
      (form (@ (action "/alien-creation-result-6"))
            (p "Do something with aliens!")
            (ol
             (li (@ (value "7"))
                 (p (b "Size & Characteristics"))
                 (ul
                  ,(roll-field-li 'size "Size" 2 6 (size-name))
                  ,(roll-field-li 'str-modifier "Strength Modifier" 2 6 (characteristic-modifier))
                  ,(roll-field-li 'dex-modifier "Dexterity Modifier" 2 6 (characteristic-modifier))
                  ,(roll-field-li 'end-modifier "Endurance Modifier" 2 6 (characteristic-modifier))
                  ,(roll-field-li 'int-modifier "Intelligence Modifier" 2 6 (characteristic-modifier))
                  ,(roll-field-li 'edu-modifier "Education Modifier" 2 6 (characteristic-modifier))
                  ,(roll-field-li 'soc-modifier "Social Modifier" 2 6 (characteristic-modifier)))
                 (br)
                 (input (@ (type "submit")
                           (value "Submit")))
                 "    "
                 (input (@ (type "reset")
                           (value "Reset")))
                 ))))))

(define-session-page "/alien-creation-result-6"
  (lambda ()
    (define major-or-minor ($session 'major-or-minor))
    (define world-size ($session 'world-size))
    (define atmosphere ($session 'atmosphere))
    (define hydrographics ($session 'hydrographics))
    (define population ($session 'population))
    (define government ($session 'government))
    (define law-level ($session 'law-level))
    (define tech-level ($session 'tech-level))
    (define starport ($session 'starport))
    (define biotype ($session 'biotype))
    (define subtype ($session 'subtype))
    (define sex ($session 'sex))
    (define reproduction ($session 'reproduction))
    (define amphibious ($session 'amphibious))
    (define locomotion ($session 'locomotion))
    (define symmetry ($session 'symmetry))
    (define legs ($session 'legs))

    (define size-roll (resolve-value size (nD 2 6)))
    (resolved-field! size (size-name size-roll))
    (resolved-field! str-modifier (resolve-field str-modifier characteristic-modifier (nD 2 6)))
    (resolved-field! dex-modifier (resolve-field dex-modifier characteristic-modifier (nD 2 6)))
    (resolved-field! end-modifier (resolve-field end-modifier characteristic-modifier (nD 2 6)))
    (resolved-field! int-modifier (resolve-field int-modifier characteristic-modifier (nD 2 6)))
    (resolved-field! edu-modifier (resolve-field edu-modifier characteristic-modifier (nD 2 6)))
    (resolved-field! soc-modifier (resolve-field soc-modifier characteristic-modifier (nD 2 6)))

    (define size-tier-n (size-tier size-roll))
    (define size-dex-n (size-dex-dice size-roll))
    (resolved-field! str-formula
      (characteristic-formula size-tier-n str-modifier (biotype-stat-modifier biotype 'Str)))
    (resolved-field! dex-formula
      (characteristic-formula size-dex-n dex-modifier (biotype-stat-modifier biotype 'Dex)))
    (resolved-field! end-formula
      (characteristic-formula size-tier-n end-modifier (biotype-stat-modifier biotype 'End)))
    (resolved-field! int-formula
      (characteristic-formula 2 int-modifier (biotype-stat-modifier biotype 'Int)))
    (resolved-field! edu-formula
      (characteristic-formula 2 edu-modifier (biotype-stat-modifier biotype 'Edu)))
    (resolved-field! soc-formula
      (characteristic-formula 2 soc-modifier (biotype-stat-modifier biotype 'Soc)))

    `((h3 "The story so far")
      "Major or Minor Race: " (b ,major-or-minor) (br)
      "World Size: " (b ,world-size) (br)
      "Atmosphere: " (b ,atmosphere) (br)
      "Hydrographics: " (b ,hydrographics) (br)
      "Population: " (b ,population) (br)
      "Government: " (b ,government) (br)
      "Law Level: " (b ,law-level) (br)
      "Tech Level: " (b ,tech-level) (br)
      "Star Port: " (b ,starport) (br)
      "Biotype: " (b ,biotype) (br)
      "Subtype: " (b ,subtype) (br)
      "Sex: " (b ,sex) (br)
      "Reproduction: " (b ,reproduction) (br)
      "Amphibious: " (b ,amphibious) (br)
      "Locomotion: " (b ,locomotion) (br)
      "Symmetry: " (b ,symmetry) (br)
      "Number of Legs: " (b ,legs) (br)
      "Size: " (b ,size) (br)
      "Strength: " (b ,str-formula) (br)
      "Dexterity: " (b ,dex-formula) (br)
      "Endurance: " (b ,end-formula) (br)
      "Intelligence: " (b ,int-formula) (br)
      "Education: " (b ,edu-formula) (br)
      "Social: " (b ,soc-formula) (br)
      (h3 "Armour & Natural Weapons")
      (form (@ (action "/alien-creation-result-7"))
            (p "Do something with aliens!")
            (ol
             (li (@ (value "8"))
                 (p (b "Armour"))
                 (ul
                  (li (b "Armour")
                      (br)
                      (input (@ (type "radio") (id "armour-roll") (name "armour")
                                (value "Roll") (checked)))
                      (label (@ (for "armour-roll"))
                             "Roll 2D6; 12+ (after Biotype/Size modifiers) grants armour, Armour Value 1D3+1")
                      (br)
                      (input (@ (type "radio") (id "armour-choose") (name "armour")
                                (value "Choose")))
                      (label (@ (for "armour-choose")) "Choose 2-12")
                      " "
                      (label (@ (for "chosen-armour")) "Chosen Armour Roll:")
                      (input (@ (type "number") (id "chosen-armour") (name "chosen-armour")
                                (min 2) (max 12)))))
                 (br))
             (li (@ (value "9"))
                 (p (b "Natural Weapons"))
                 (ul
                  (li (b "Natural Weapon")
                      (br)
                      (input (@ (type "radio") (id "natural-weapon-roll") (name "natural-weapon")
                                (value "Roll") (checked)))
                      (label (@ (for "natural-weapon-roll"))
                             "Roll 2D6; 9+ (after Biotype modifier) retains a natural weapon, form rolled separately")
                      (br)
                      (input (@ (type "radio") (id "natural-weapon-choose") (name "natural-weapon")
                                (value "Choose")))
                      (label (@ (for "natural-weapon-choose")) "Choose 2-12")
                      " "
                      (label (@ (for "chosen-natural-weapon")) "Chosen Natural Weapon Roll:")
                      (input (@ (type "number") (id "chosen-natural-weapon") (name "chosen-natural-weapon")
                                (min 2) (max 12))))
                  )
                 (br)
                 (input (@ (type "submit")
                           (value "Submit")))
                 "    "
                 (input (@ (type "reset")
                           (value "Reset")))
                 ))))))

(define-session-page "/alien-creation-result-7"
  (lambda ()
    (define major-or-minor ($session 'major-or-minor))
    (define world-size ($session 'world-size))
    (define atmosphere ($session 'atmosphere))
    (define hydrographics ($session 'hydrographics))
    (define population ($session 'population))
    (define government ($session 'government))
    (define law-level ($session 'law-level))
    (define tech-level ($session 'tech-level))
    (define starport ($session 'starport))
    (define biotype ($session 'biotype))
    (define subtype ($session 'subtype))
    (define sex ($session 'sex))
    (define reproduction ($session 'reproduction))
    (define amphibious ($session 'amphibious))
    (define locomotion ($session 'locomotion))
    (define symmetry ($session 'symmetry))
    (define legs ($session 'legs))
    (define size ($session 'size))
    (define str-formula ($session 'str-formula))
    (define dex-formula ($session 'dex-formula))
    (define end-formula ($session 'end-formula))
    (define int-formula ($session 'int-formula))
    (define edu-formula ($session 'edu-formula))
    (define soc-formula ($session 'soc-formula))
    (resolved-field! armour (resolve-field armour (lambda (roll) (resolve-armour roll biotype size)) (nD 2 6)))
    (resolved-field! natural-weapon
      (resolve-field natural-weapon (lambda (roll) (resolve-natural-weapon roll biotype)) (nD 2 6)))

    `((h3 "The story so far")
      "Major or Minor Race: " (b ,major-or-minor) (br)
      "World Size: " (b ,world-size) (br)
      "Atmosphere: " (b ,atmosphere) (br)
      "Hydrographics: " (b ,hydrographics) (br)
      "Population: " (b ,population) (br)
      "Government: " (b ,government) (br)
      "Law Level: " (b ,law-level) (br)
      "Tech Level: " (b ,tech-level) (br)
      "Star Port: " (b ,starport) (br)
      "Biotype: " (b ,biotype) (br)
      "Subtype: " (b ,subtype) (br)
      "Sex: " (b ,sex) (br)
      "Reproduction: " (b ,reproduction) (br)
      "Amphibious: " (b ,amphibious) (br)
      "Locomotion: " (b ,locomotion) (br)
      "Symmetry: " (b ,symmetry) (br)
      "Number of Legs: " (b ,legs) (br)
      "Size: " (b ,size) (br)
      "Strength: " (b ,str-formula) (br)
      "Dexterity: " (b ,dex-formula) (br)
      "Endurance: " (b ,end-formula) (br)
      "Intelligence: " (b ,int-formula) (br)
      "Education: " (b ,edu-formula) (br)
      "Social: " (b ,soc-formula) (br)
      "Armour: " (b ,armour) (br)
      "Natural Weapon: " (b ,natural-weapon) (br)
      (h3 "Senses")
      (form (@ (action "/alien-creation-result-8"))
            (p "Do something with aliens!")
            (ol
             (li (@ (value "10"))
                 (p (b "Senses"))
                 (ul
                  ,(roll-field-li 'vision "Vision" 2 6 (vision-name))
                  ,(roll-field-li 'audio "Audio" 2 6 (audio-name))
                  ,(roll-field-li 'olfactory "Olfactory" 2 6 (olfactory-name))
                  (li (b "Special Sense")
                      (br)
                      (input (@ (type "radio") (id "special-sense-roll") (name "special-sense")
                                (value "Roll") (checked)))
                      (label (@ (for "special-sense-roll"))
                             "Roll 2D6; 11+ grants a Special Sense, rolled separately on 1D6")
                      (br)
                      (input (@ (type "radio") (id "special-sense-choose") (name "special-sense")
                                (value "Choose")))
                      (label (@ (for "special-sense-choose")) "Choose 2-12")
                      " "
                      (label (@ (for "chosen-special-sense")) "Chosen Special Sense Roll:")
                      (input (@ (type "number") (id "chosen-special-sense") (name "chosen-special-sense")
                                (min 2) (max 12)))))
                 (br)
                 (input (@ (type "submit")
                           (value "Submit")))
                 "    "
                 (input (@ (type "reset")
                           (value "Reset")))
                 ))))))

(define-session-page "/alien-creation-result-8"
  (lambda ()
    (define major-or-minor ($session 'major-or-minor))
    (define world-size ($session 'world-size))
    (define atmosphere ($session 'atmosphere))
    (define hydrographics ($session 'hydrographics))
    (define population ($session 'population))
    (define government ($session 'government))
    (define law-level ($session 'law-level))
    (define tech-level ($session 'tech-level))
    (define starport ($session 'starport))
    (define biotype ($session 'biotype))
    (define subtype ($session 'subtype))
    (define sex ($session 'sex))
    (define reproduction ($session 'reproduction))
    (define amphibious ($session 'amphibious))
    (define locomotion ($session 'locomotion))
    (define symmetry ($session 'symmetry))
    (define legs ($session 'legs))
    (define size ($session 'size))
    (define str-formula ($session 'str-formula))
    (define dex-formula ($session 'dex-formula))
    (define end-formula ($session 'end-formula))
    (define int-formula ($session 'int-formula))
    (define edu-formula ($session 'edu-formula))
    (define soc-formula ($session 'soc-formula))
    (define armour ($session 'armour))
    (define natural-weapon ($session 'natural-weapon))
    (resolved-field! vision (resolve-field vision vision-name (nD 2 6)))
    (resolved-field! audio (resolve-field audio audio-name (nD 2 6)))
    (resolved-field! olfactory (resolve-field olfactory olfactory-name (nD 2 6)))
    (resolved-field! special-sense (resolve-field special-sense resolve-special-sense (nD 2 6)))

    `((h3 "The story so far")
      "Major or Minor Race: " (b ,major-or-minor) (br)
      "World Size: " (b ,world-size) (br)
      "Atmosphere: " (b ,atmosphere) (br)
      "Hydrographics: " (b ,hydrographics) (br)
      "Population: " (b ,population) (br)
      "Government: " (b ,government) (br)
      "Law Level: " (b ,law-level) (br)
      "Tech Level: " (b ,tech-level) (br)
      "Star Port: " (b ,starport) (br)
      "Biotype: " (b ,biotype) (br)
      "Subtype: " (b ,subtype) (br)
      "Sex: " (b ,sex) (br)
      "Reproduction: " (b ,reproduction) (br)
      "Amphibious: " (b ,amphibious) (br)
      "Locomotion: " (b ,locomotion) (br)
      "Symmetry: " (b ,symmetry) (br)
      "Number of Legs: " (b ,legs) (br)
      "Size: " (b ,size) (br)
      "Strength: " (b ,str-formula) (br)
      "Dexterity: " (b ,dex-formula) (br)
      "Endurance: " (b ,end-formula) (br)
      "Intelligence: " (b ,int-formula) (br)
      "Education: " (b ,edu-formula) (br)
      "Social: " (b ,soc-formula) (br)
      "Armour: " (b ,armour) (br)
      "Natural Weapon: " (b ,natural-weapon) (br)
      "Vision: " (b ,vision) (br)
      "Audio: " (b ,audio) (br)
      "Olfactory: " (b ,olfactory) (br)
      "Special Sense: " (b ,special-sense) (br)
      (h3 "Life Cycle")
      (form (@ (action "/alien-creation-result-9"))
            (p "Do something with aliens!")
            (ol
             (li (@ (value "12"))
                 (p (b "Life Cycle"))
                 (ul
                  (li (b "Lifespan")
                      (br)
                      (input (@ (type "radio") (id "lifespan-roll") (name "lifespan")
                                (value "Roll") (checked)))
                      (label (@ (for "lifespan-roll"))
                             "Roll 2D6: 2-4 Very Short (2D6 yrs), 5 Short (40), 6-7 Human-level (80), 8-10 Long (200), 11 Very Long (1000), 12 Immortal?")
                      (br)
                      (input (@ (type "radio") (id "lifespan-choose") (name "lifespan")
                                (value "Choose")))
                      (label (@ (for "lifespan-choose")) "Choose 2-12")
                      " "
                      (label (@ (for "chosen-lifespan")) "Chosen Lifespan Roll:")
                      (input (@ (type "number") (id "chosen-lifespan") (name "chosen-lifespan")
                                (min 2) (max 12))))
                  (li (b "Physiological Advantage")
                      (br)
                      (input (@ (type "radio") (id "physiological-advantage-roll") (name "physiological-advantage")
                                (value "Roll") (checked)))
                      (label (@ (for "physiological-advantage-roll"))
                             "Roll 2D6; 9+ grants a Physiological Advantage, rolled separately on 1D6")
                      (br)
                      (input (@ (type "radio") (id "physiological-advantage-choose") (name "physiological-advantage")
                                (value "Choose")))
                      (label (@ (for "physiological-advantage-choose")) "Choose 2-12")
                      " "
                      (label (@ (for "chosen-physiological-advantage")) "Chosen Physiological Advantage Roll:")
                      (input (@ (type "number") (id "chosen-physiological-advantage")
                                (name "chosen-physiological-advantage")
                                (min 2) (max 12)))))
                 (br)
                 (input (@ (type "submit")
                           (value "Submit")))
                 "    "
                 (input (@ (type "reset")
                           (value "Reset")))
                 ))))))

(define-session-page "/alien-creation-result-9"
  (lambda ()
    (define major-or-minor ($session 'major-or-minor))
    (define world-size ($session 'world-size))
    (define atmosphere ($session 'atmosphere))
    (define hydrographics ($session 'hydrographics))
    (define population ($session 'population))
    (define government ($session 'government))
    (define law-level ($session 'law-level))
    (define tech-level ($session 'tech-level))
    (define starport ($session 'starport))
    (define biotype ($session 'biotype))
    (define subtype ($session 'subtype))
    (define sex ($session 'sex))
    (define reproduction ($session 'reproduction))
    (define amphibious ($session 'amphibious))
    (define locomotion ($session 'locomotion))
    (define symmetry ($session 'symmetry))
    (define legs ($session 'legs))
    (define size ($session 'size))
    (define str-formula ($session 'str-formula))
    (define dex-formula ($session 'dex-formula))
    (define end-formula ($session 'end-formula))
    (define int-formula ($session 'int-formula))
    (define edu-formula ($session 'edu-formula))
    (define soc-formula ($session 'soc-formula))
    (define armour ($session 'armour))
    (define natural-weapon ($session 'natural-weapon))
    (define vision ($session 'vision))
    (define audio ($session 'audio))
    (define olfactory ($session 'olfactory))
    (define special-sense ($session 'special-sense))
    (resolved-field! lifespan (resolve-field lifespan resolve-lifespan (nD 2 6)))
    (resolved-field! physiological-advantage
      (resolve-field physiological-advantage resolve-physiological-advantage (nD 2 6)))

    `((h3 "The story so far")
      "Major or Minor Race: " (b ,major-or-minor) (br)
      "World Size: " (b ,world-size) (br)
      "Atmosphere: " (b ,atmosphere) (br)
      "Hydrographics: " (b ,hydrographics) (br)
      "Population: " (b ,population) (br)
      "Government: " (b ,government) (br)
      "Law Level: " (b ,law-level) (br)
      "Tech Level: " (b ,tech-level) (br)
      "Star Port: " (b ,starport) (br)
      "Biotype: " (b ,biotype) (br)
      "Subtype: " (b ,subtype) (br)
      "Sex: " (b ,sex) (br)
      "Reproduction: " (b ,reproduction) (br)
      "Amphibious: " (b ,amphibious) (br)
      "Locomotion: " (b ,locomotion) (br)
      "Symmetry: " (b ,symmetry) (br)
      "Number of Legs: " (b ,legs) (br)
      "Size: " (b ,size) (br)
      "Strength: " (b ,str-formula) (br)
      "Dexterity: " (b ,dex-formula) (br)
      "Endurance: " (b ,end-formula) (br)
      "Intelligence: " (b ,int-formula) (br)
      "Education: " (b ,edu-formula) (br)
      "Social: " (b ,soc-formula) (br)
      "Armour: " (b ,armour) (br)
      "Natural Weapon: " (b ,natural-weapon) (br)
      "Vision: " (b ,vision) (br)
      "Audio: " (b ,audio) (br)
      "Olfactory: " (b ,olfactory) (br)
      "Special Sense: " (b ,special-sense) (br)
      "Lifespan: " (b ,lifespan) (br)
      "Physiological Advantage: " (b ,physiological-advantage) (br)
      (h3 "Interpretation")
      (p "Write up a summary of the alien species: what do these results say about how the race lives today, and how has their evolution or physiology shaped their society and outlook?"))))
)
