;;; cu-arcs-v2.scm -- Cepheus Universal Alien Race creation System, version 2.
;;; Creates intelligent aliens.
;;;
;;; awful --port=2020 cu-arcs-v2.scm
(module cu-arcs ()

(import scheme)
(import (chicken base))
(import (chicken random))
(import (math base))
(import loop)
(import srfi-13)
(import awful)

(include "roll-tables.scm")

(define (D num-sides) (+ 1 (pseudo-random-integer num-sides)))
(define (nD num-dice num-sides)
  (sum (loop repeat num-dice collect (D num-sides))))

(define bob "Hi, I'm Bob!")

;; Race Biotype & Subtype, Cepheus Universal p. 329.
(define-roll-table (biotype-name roll)
  ((2 . 3) "Scavenger")
  ((4 . 5) "Herbivore")
  ((6 . 10) "Omnivore")
  ((11 . 12) "Carnivore"))

(define-keyed-roll-table (subtype-name biotype roll)
  ("Scavenger" ((2 . 3) "Reducer")
               ((4 . 7) "Hijacker")
               ((8 . 9) "Intimidator")
               ((10 . 12) "Carrion Eater"))
  ("Herbivore" ((2) "Filter")
               ((3 . 7) "Intermittent")
               ((8 . 12) "Grazer"))
  ("Omnivore" ((2 . 7) "Gatherer")
              ((8 . 10) "Hunter")
              ((11 . 12) "Eater"))
  ("Carnivore" ((2 . 5) "Pouncer")
               ((6 . 8) "Chaser")
               ((9 . 11) "Killer")
               ((12) "Siren")))

(define-session-page (main-page-path)
  (lambda ()
    `((h3 "Alien Race Creation - Major or Minor Race")
      (form (@ (action "/major-minor-result"))
            (p "Do something with aliens!")
            (ol
             (li
              (p (b "Major or Minor Race"))
              (input (@ (type "radio")
                        (id "major-or-minor-major")
                        (name "major-or-minor")
                        (value "Major")
                        (checked)))
              (label (@ (for "major-or-minor-major"))
                     "Major")
              (input (@ (type "radio")
                        (id "major-or-minor-minor")
                        (name "major-or-minor")
                        (value "Minor")))
              (label (@ (for "major-or-minor-minor"))
                     "Minor")
              (br)
              (input (@ (type "submit")
                        (value "Submit")))
              "    "
              (input (@ (type "reset")
                        (value "Reset")))))))))

(define-session-page "/major-minor-result"
  (lambda ()
    (define major-or-minor (if (string=? ($ "major-or-minor") "Major")
                               'Major
                               'Minor))
    ($session-set! 'major-or-minor major-or-minor)
    `((h3 "The story so far")
      (p
       "Major or Minor Race: " (b ,($session 'major-or-minor)) (br))
       
      (h3 "Alien Race Creation - Homeworld")
      (form (@ (action "/alien-creation-result"))
            (p "Do something with aliens!")
            (ol

             (li (@ (value "2"))
              (p (b "Homeworld"))
              (ul
               (li (b "World Size")
                   (input (@ (type "radio")
                             (id "world-size-roll")
                             (name "world-size")
                             (value "Roll")
                             (checked)))
                   (label (@ (for "world-size-roll"))
                          "Roll 2D6+1")
                   (input (@ (type "radio")
                             (id "world-size-choose")
                             (name "world-size")
                             (value "Choose")))
                   (label (@ (for "world-size-chose"))
                          "Choose World Size: ")
                   " "
                   (label (@ (for "chosen-world-size"))
                          "3-13:")
                   (input (@ (type "number")
                             (id "chosen-world-size")
                             (name "chosen-world-size")
                             (min 3)
                             (max 13))))

               (li (b "Atmosphere")
                   (br)
                   (input (@ (type "radio")
                             (id "atmosphere-roll")
                             (name "atmosphere")
                             (value "Roll")
                             (checked)))
                   (label (@ (for "atmosphere-roll"))
                          "Roll 2D6; if Size 3-4 then roll 1D6+1")
                   (br)
                   (input (@ (type "radio")
                             (id "atmosphere-choose")
                             (name "atmosphere")
                             (value "Choose")))
                   (label (@ (for "atmosphere-choose"))
                          "Choose 2-12; if Size 3-4 then choose 2-7")
                   " "
                   (label (@ (for "chosen-atmosphere"))
                          "Chosen Atmosphere:")
                   (input (@ (type "number")
                             (id "chosen-atmosphere")
                             (name "chosen-atmosphere")
                             (min 2)
                             (max 12))))

               (li (b "Hydrographics")
                   (br)
                   (input (@ (type "radio")
                             (id "hydrographics-roll")
                             (name "hydrographics")
                             (value "Roll")
                             (checked)))
                   (label (@ (for "hydrographics-roll"))
                          "Roll 2D6-2; if Atmosphere 2-3 roll 1D6+1")
                   (br)
                   (input (@ (type "radio")
                             (id "hydrographics-choose")
                             (name "hydrographics")
                             (value "Choose")))
                   (label (@ (for "hydrographics-choose"))
                          "Choose: 0-10; if Atmosphere 2-3 choose 2-7")
                   " "
                   (label (@ (for "chosen-hydrographics"))
                          "Chosen Hydrographics:")
                   (input (@ (type "number")
                             (id "chosen-hydrographics")
                             (name "chosen-hydrographics")
                             (min 0)
                             (max 10))))

               (li (b "Population")
                   (br)
                   (input (@ (type "radio")
                             (id "population-roll")
                             (name "population")
                             (value "Roll")
                             (checked)))
                   (label (@ (for "population-roll"))
                          "If Minor Race roll 1D3+5; if Major Race roll 1D3+7")
                   (br)
                   (input (@ (type "radio")
                             (id "population-choose")
                             (name "population")
                             (value "Choose")))
                   (label (@ (for "population-choose"))
                          "If Minor Race choose 6-8; 
if Major race choose 8-10")
                   " "
                   (label (@ (for "chosen-population"))
                          "Chosen Population:")
                   (input (@ (type "number")
                             (id "chosen-population")
                             (name "chosen-population")
                             (min 6)
                             (max 10))))

               (li (b "Government")
                   (br)
                   (input (@ (type "radio")
                             (id "government-roll")
                             (name "government")
                             (value "Roll")
                             (checked)))
                   (label (@ (for "government-roll"))
                          "Roll 1D6, then on 1-3 roll 1D6+1
or on 4-6 roll 1D6+7")                  
                   (br)
                   (input (@ (type "radio")
                             (id "government-choose")
                             (name "government")
                             (value "Choose")))
                   (label (@ (for "government-choose"))
                          "Choose from 2-7 or 8-13")
                   " "
                   (label (@ (for "chosen-government"))
                          "Chosen Goverment:")
                   (input (@ (type "number")
                             (id "chosen-government")
                             (name "chosen-government")
                             (min 2)
                             (max 13))))

               (li (b "Law Level")
                   (br)
                   (input (@ (type "radio")
                             (id "law-level-roll")
                             (name "law-level")
                             (value "Roll")
                             (checked)))
                   (label (@ (for "law-level-roll"))
                          "Roll 2D6-2")
                   (br)
                   (input (@ (type "radio")
                             (id "law-level-choose")
                             (name "law-level")
                             (value "Choose")))
                   (label (@ (for "law-level-choose"))
                          "Choose 0-10")
                   " "
                   (label (@ (for "chosen-law-level"))
                          "Chosen Law Level:")
                   (input (@ (type "number")
                             (id "chosen-law-level")
                             (name "chosen-law-level")
                             (min 0)
                             (max 10))))

               (li (b "Tech Level")
                   (br)
                   (input (@ (type "radio")
                             (id "tech-level-roll")
                             (name "tech-level")
                             (value "Roll")
                             (checked)))
                   (label (@ (for "tech-level-roll"))
                          "If Major Race roll 1D6+9, otherwise "
                          "If Minor Race roll 1D6, then "
                          "on 1-3 Primitive, roll 1D3, "
                          "on 4-5 Low Tech, roll 1D3+3, "
                          "on 6 Mid Tech, roll 1D3+6")
                   (br)
                   (input (@ (type "radio")
                             (id "tech-level-choose")
                             (name "tech-level")
                             (value "Choose")))
                   (label (@ (for "tech-level-choose"))
                          "Major Race: Choose 10-15, otherwise "
                          "Minor Race: Choose Primitive 1-3, Low Tech 4-6,
Mid Tech 7-9")
                   " "
                   (label (@ (for "chosen-tech-level"))
                          "Chosen Tech Level:")
                   (input (@ (type "number")
                             (id "chosen-tech-level")
                             (name "chosen-tech-level")
                             (min 1)
                             (max 15))))

               (li (b "Starport")
                   (br)
                   (input (@ (type "radio")
                             (id "starport-roll")
                             (name "starport")
                             (value "Roll")
                             (checked)))
                   (label (@ (for "starport-roll"))
                          "If Major Race Class A, otherwise "
                          "If Minor Race roll 1D6, then "
                          "on 1-2 Class X, "
                          "on 3 Class E, "
                          "on 4 Class D, "
                          "on 5 Class C, "
                          "on 6 Class B")
                   (br)
                   (input (@ (type "radio")
                             (id "starport-choose")
                             (name "starport")
                             (value "Choose")))
                   (label (@ (for "starport-choose"))
                          "Major Race: Class A; otherwise "
                          "Minor Race: Choose X, E, D, C, or B")
                   " "
                   (label (@ (for "chosen-starport"))
                          "Chosen Tech Level:")
                   (input (@ (type "text")
                             (id "chosen-starport")
                             (name "chosen-starport")
                             (pattern "[XxEeDdCcBb]")))))
              (br)
              (input (@ (type "submit")
                        (value "Submit")))
              "    "
              (input (@ (type "reset")
                        (value "Reset")))))))))

(define-session-page "/alien-creation-result"
  (lambda ()
    (define major-or-minor ($session 'major-or-minor))
    (define world-size (if (string=? ($ "world-size") "Roll")
                           (+ (nD 2 6) 1)
                           (string->number ($ "chosen-world-size"))))
    ($session-set! 'world-size world-size)
    (define atmosphere (if (string=? ($ "atmosphere") "Roll")
                           (if (<= 3 world-size 4)
                               (+ (D 6) 1)
                               (nD 2 6))
                           (string->number ($ "chosen-atmosphere"))))
    ($session-set! 'atmosphere atmosphere)
    (define hydrographics (if (string=? ($ "hydrographics") "Roll")
                              (if (<= 2 atmosphere 3)
                                  (+ (D 6) 1)
                                  (- (nD 2 6) 2))
                              (string->number ($ "chosen-hydrographics"))))
    ($session-set! 'hydrographics hydrographics)
    (define population (if (string=? ($ "population") "Roll")
                           (if (eq? major-or-minor 'Minor)
                               (+ (D 3) 5)
                               (+ (D 3) 7))
                           (string->number ($ "chosen-population"))))
    ($session-set! 'population population)
    (define government (if (string=? ($ "government") "Roll")
                           (if (<= 1 (D 6) 3)
                               (+ (D 6) 1)
                               (+ (D 6) 7))
                           (string->number ($ "chosen-government"))))
    ($session-set! 'government government)

    (define law-level (if (string=? ($ "law-level") "Roll")
                          (- (nD 2 6) 2)
                          (string->number ($ "chosen-law-level"))))
    ($session-set! 'law-level law-level)
    (define tech-level (if (string=? ($ "tech-level") "Roll")
                           (if (eq? major-or-minor 'Major)
                               (+ (D 6) 9)
                               (let ((roll (D 6)))
                                 (cond ((<= 1 roll 3)
                                        (D 3))
                                       ((<= 4 roll 5)
                                        (+ (D 3) 3))
                                       ((= roll 6)
                                        (+ (D 3) 6))
                                       (else
                                        (error "Impossible in tech-level")))))
                           (string->number ($ "chosen-tech-level"))))
    ($session-set! 'tech-level tech-level)
    (define starport (if (string=? ($ "starport") "Roll")
                         (if (eq? major-or-minor 'Major)
                             "A"
                             (let ((roll (D 6)))
                               (cond ((<= 1 roll 2)
                                      "X")
                                     ((= roll 3)
                                      "E")
                                     ((= roll 4)
                                      "D")
                                     ((= roll 5)
                                      "C")
                                     ((= roll 6)
                                      "B"))))
                         (string-upcase ($ "chosen-starport"))))
    ($session-set! 'starport starport)
                             
    `((h3 "The story so far")
      "Major or Minor Race: " (b ,major-or-minor) (br)
      "World Size: " (b ,world-size) (br)
      "Atmosphere: " (b ,atmosphere) (br)
      "Hydrographics: " (b ,hydrographics) (br)
      "Population: " (b ,population) (br)
      "Government: " (b ,government) (br)
      "Law Level: " (b ,law-level) (br)
      "Tech Level: " (b ,tech-level) (br)
      "Star Port: " (b ,starport) (br)
      (h3 "Biotype")
      ;; Another input form
      (form (@ (action "/alien-creation-result-2"))
            (p "Do something with aliens!")
            (ol

             (li (@ (value "3"))
                 (p (b "Biotype"))
                 (ul
                  ,(roll-field-li 'biotype "Biotype" 2 6 (biotype-name))
                  ,(keyed-roll-field-li 'subtype "Subtype" 2 6 "Biotype" (subtype-name))
                  )
                 (br)
                 (input (@ (type "submit")
                           (value "Submit")))
                 "    "
                 (input (@ (type "reset")
                           (value "Reset")))
                 ))))))

(define-session-page "/alien-creation-result-2"
  (lambda ()
    (define major-or-minor ($session 'major-or-minor))
    (define world-size ($session 'world-size))
    (define atmosphere ($session 'atmosphere))
    (define hydrographics ($session 'hydrographics))
    (define population ($session 'population))
    (define government ($session 'government))
    (define law-level ($session 'law-level))
    (define tech-level ($session 'tech-level))
    (define starport ($session 'starport))
    (define biotype (resolve-field biotype biotype-name (nD 2 6)))
    ($session-set! 'biotype biotype)
    (define subtype (resolve-keyed-field subtype subtype-name biotype (nD 2 6)))
    ($session-set! 'subtype subtype)

    `((h3 "The story so far")
      "Major or Minor Race: " (b ,major-or-minor) (br)
      "World Size: " (b ,world-size) (br)
      "Atmosphere: " (b ,atmosphere) (br)
      "Hydrographics: " (b ,hydrographics) (br)
      "Population: " (b ,population) (br)
      "Government: " (b ,government) (br)
      "Law Level: " (b ,law-level) (br)
      "Tech Level: " (b ,tech-level) (br)
      "Star Port: " (b ,starport) (br)
      "Biotype: " (b ,biotype) (br)
      "Subtype: " (b ,subtype) (br)
      )))
)
